#!/usr/bin/env python3
"""
OrcheNet MikroTik Provisioning Script Generator

This script generates a customized provisioning script for a MikroTik router
by fetching configuration from the OrcheNet server.

Usage:
    python generate-provision-script.py --device-id 1 --server https://orchenet.example.com:8000

Requirements:
    pip install requests
"""

import argparse
import requests
import sys
import subprocess
from pathlib import Path


def generate_wireguard_keypair():
    """Generate a WireGuard key pair using wg command"""
    try:
        # Generate private key
        private_key = subprocess.check_output(["wg", "genkey"], text=True).strip()

        # Generate public key from private key
        public_key = subprocess.check_output(
            ["wg", "pubkey"],
            input=private_key,
            text=True
        ).strip()

        return private_key, public_key
    except FileNotFoundError:
        print("Error: 'wg' command not found. Please install wireguard-tools.")
        sys.exit(1)
    except Exception as e:
        print(f"Error generating WireGuard keys: {e}")
        sys.exit(1)


def get_server_info(api_url):
    """Get WireGuard server information from OrcheNet API"""
    try:
        response = requests.get(f"{api_url}/api/wireguard/info", verify=False)
        response.raise_for_status()
        return response.json()
    except requests.exceptions.RequestException as e:
        print(f"Error fetching server info: {e}")
        sys.exit(1)


def enable_wireguard_for_device(api_url, device_id, public_key):
    """Enable WireGuard for a device via OrcheNet API"""
    try:
        response = requests.post(
            f"{api_url}/api/wireguard/peers",
            json={"device_id": device_id, "public_key": public_key},
            verify=False
        )
        response.raise_for_status()
        return response.json()
    except requests.exceptions.RequestException as e:
        print(f"Error enabling WireGuard: {e}")
        sys.exit(1)


def generate_provisioning_script(
    server_ip,
    server_port,
    server_public_key,
    device_private_key,
    device_vpn_ip,
    api_url,
    output_file
):
    """Generate the provisioning script with provided configuration"""

    script_template = f'''# OrcheNet MikroTik Provisioning Script
# Generated by generate-provision-script.py
# This script sets up a MikroTik router to connect to an OrcheNet server via WireGuard

# Variables - DO NOT EDIT (generated automatically)
:local orchenetServer "{server_ip}"
:local orchenetPort "{server_port}"
:local orchenetServerPublicKey "{server_public_key}"
:local devicePrivateKey "{device_private_key}"
:local deviceVpnIp "{device_vpn_ip}/32"
:local apiUrl "{api_url}/api/checkin"
:local deviceName [/system identity get name]
:local sshUser "orchenet"
:local sshPassword "CHANGE_ME_TO_SECURE_PASSWORD"

# ==========================================
# Script begins
# ==========================================

:put "===== OrcheNet Provisioning Script ====="
:put "Device: $deviceName"
:put "Server: $orchenetServer"
:put ""

# 1. Configure WireGuard Interface
:put "Step 1: Configuring WireGuard interface..."
:do {{
    /interface wireguard add name=orchenet-wg private-key=$devicePrivateKey listen-port=51821
    :put "  - WireGuard interface created"
}} on-error={{
    :put "  - WireGuard interface already exists or failed to create"
}}

# 2. Configure WireGuard Peer (OrcheNet Server)
:put "Step 2: Adding OrcheNet server as WireGuard peer..."
:do {{
    /interface wireguard peers add interface=orchenet-wg \\
        public-key=$orchenetServerPublicKey \\
        endpoint-address=$orchenetServer \\
        endpoint-port=$orchenetPort \\
        allowed-address=10.99.0.0/24 \\
        persistent-keepalive=25s
    :put "  - Server peer added"
}} on-error={{
    :put "  - Peer already exists or failed to add"
}}

# 3. Assign IP Address to WireGuard Interface
:put "Step 3: Assigning IP address to WireGuard interface..."
:do {{
    /ip address add address=$deviceVpnIp interface=orchenet-wg
    :put "  - IP address assigned: $deviceVpnIp"
}} on-error={{
    :put "  - IP address already exists or failed to assign"
}}

# 4. Add Route to OrcheNet Server via WireGuard
:put "Step 4: Adding route to OrcheNet network..."
:do {{
    /ip route add dst-address=10.99.0.0/24 gateway=orchenet-wg
    :put "  - Route added"
}} on-error={{
    :put "  - Route already exists or failed to add"
}}

# 5. Create SSH User for OrcheNet
:put "Step 5: Creating SSH user for OrcheNet..."
:do {{
    /user add name=$sshUser password=$sshPassword group=full
    :put "  - User '$sshUser' created"
    :put "  ! IMPORTANT: Change the password immediately or use SSH keys!"
}} on-error={{
    :put "  - User already exists or failed to create"
}}

# 6. Enable SSH Service
:put "Step 6: Enabling SSH service..."
:do {{
    /ip service set ssh disabled=no port=22
    :put "  - SSH service enabled on port 22"
}} on-error={{
    :put "  - SSH service configuration failed"
}}

# 7. Add Firewall Rule to Allow SSH from OrcheNet VPN
:put "Step 7: Configuring firewall for OrcheNet access..."
:do {{
    /ip firewall filter add chain=input protocol=tcp dst-port=22 \\
        src-address=10.99.0.0/24 in-interface=orchenet-wg \\
        action=accept place-before=0 comment="Allow SSH from OrcheNet"
    :put "  - Firewall rule added"
}} on-error={{
    :put "  - Firewall rule already exists or failed to add"
}}

# 8. Create Check-in Script
:put "Step 8: Creating check-in script..."
:do {{
    /system script add name=orchenet-checkin owner=admin policy=read,write,policy,test source={{
        :local apiUrl "$apiUrl"
        :local deviceName [/system identity get name]
        :local serialNumber [/system routerboard get serial-number]
        :local firmwareVersion [/system package get system version]
        :local uptimeSeconds [/system resource get uptime]
        :local cpuLoad [/system resource get cpu-load]
        :local freeMemory [/system resource get free-memory]
        :local totalMemory [/system resource get total-memory]
        :local wgStatus ""
        :if ([/interface get orchenet-wg running]) do={{
            :set wgStatus "up"
        }} else={{
            :set wgStatus "down"
        }}
        :local jsonData "{{\\\"device_name\\\":\\\"$deviceName\\\",\\\"vendor\\\":\\\"mikrotik\\\",\\\"serial_number\\\":\\\"$serialNumber\\\",\\\"firmware_version\\\":\\\"$firmwareVersion\\\",\\\"status_data\\\":{{\\\"uptime\\\":$uptimeSeconds,\\\"cpu_load\\\":$cpuLoad,\\\"free_memory\\\":$freeMemory,\\\"total_memory\\\":$totalMemory,\\\"wireguard_status\\\":\\\"$wgStatus\\\"}}}}"
        :do {{
            /tool fetch url=$apiUrl mode=https http-method=post http-header-field="Content-Type: application/json" http-data=$jsonData dst-path=checkin-response.json
            :log info "OrcheNet: Check-in successful"
        }} on-error={{
            :log error "OrcheNet: Check-in failed"
        }}
    }}
    :put "  - Check-in script created"
}} on-error={{
    :put "  - Check-in script already exists or failed to create"
}}

# 9. Schedule Check-in Script
:put "Step 9: Scheduling automatic check-ins..."
:do {{
    /system scheduler add name=orchenet-checkin \\
        interval=5m \\
        on-event="/system script run orchenet-checkin" \\
        start-time=startup \\
        comment="OrcheNet periodic check-in"
    :put "  - Scheduler created (5 minute interval)"
}} on-error={{
    :put "  - Scheduler already exists or failed to create"
}}

# 10. Test WireGuard Connection
:put "Step 10: Testing WireGuard connection..."
:delay 2s
:if ([/interface get orchenet-wg running]) do={{
    :put "  - WireGuard interface is UP"
    :do {{
        /ping {server_ip} count=3
        :put "  - Ping to OrcheNet server successful"
    }} on-error={{
        :put "  ! WARNING: Ping to OrcheNet server failed"
    }}
}} else={{
    :put "  ! WARNING: WireGuard interface is DOWN"
}}

:put ""
:put "===== Provisioning Complete ====="
:put "Device VPN IP: {device_vpn_ip}"
:put "Server VPN IP: {server_ip}"
:put ""
:put "Next Steps:"
:put "  1. Change SSH password: /user set $sshUser password=NEW_PASSWORD"
:put "  2. Verify device in OrcheNet web interface"
:put "  3. Test SSH: ssh {sshUser}@{device_vpn_ip}"
:put ""
'''

    with open(output_file, 'w') as f:
        f.write(script_template)

    print(f"✓ Provisioning script generated: {output_file}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate MikroTik provisioning script for OrcheNet"
    )
    parser.add_argument(
        "--device-id",
        type=int,
        required=True,
        help="Device ID in OrcheNet database"
    )
    parser.add_argument(
        "--server",
        required=True,
        help="OrcheNet server URL (e.g., https://orchenet.example.com:8000)"
    )
    parser.add_argument(
        "--output",
        default="provision-device.rsc",
        help="Output file name (default: provision-device.rsc)"
    )
    parser.add_argument(
        "--server-ip",
        help="Server public IP address (if different from --server hostname)"
    )

    args = parser.parse_args()

    api_url = args.server.rstrip('/')

    # Extract server IP from URL if not provided
    server_ip = args.server_ip
    if not server_ip:
        from urllib.parse import urlparse
        parsed = urlparse(api_url)
        server_ip = parsed.hostname

    print("OrcheNet MikroTik Provisioning Script Generator")
    print("=" * 50)
    print(f"Server: {api_url}")
    print(f"Device ID: {args.device_id}")
    print()

    # Step 1: Get server WireGuard info
    print("Fetching OrcheNet server information...")
    server_info = get_server_info(api_url)
    print(f"✓ Server Public Key: {server_info['server_public_key'][:20]}...")
    print(f"✓ Server VPN IP: {server_info['server_ip']}")
    print(f"✓ Listen Port: {server_info['listen_port']}")
    print()

    # Step 2: Generate WireGuard keypair for device
    print("Generating WireGuard keypair for device...")
    device_private_key, device_public_key = generate_wireguard_keypair()
    print(f"✓ Device Public Key: {device_public_key[:20]}...")
    print()

    # Step 3: Enable WireGuard for device
    print("Registering device with OrcheNet...")
    peer_info = enable_wireguard_for_device(api_url, args.device_id, device_public_key)
    print(f"✓ Device Name: {peer_info['device_name']}")
    print(f"✓ Assigned VPN IP: {peer_info['private_ip']}")
    print()

    # Step 4: Generate provisioning script
    print("Generating provisioning script...")
    generate_provisioning_script(
        server_ip=server_ip,
        server_port=server_info['listen_port'],
        server_public_key=server_info['server_public_key'],
        device_private_key=device_private_key,
        device_vpn_ip=peer_info['private_ip'],
        api_url=api_url,
        output_file=args.output
    )
    print()

    print("=" * 50)
    print("SUCCESS! Next steps:")
    print()
    print("1. Copy the script to your MikroTik router:")
    print(f"   scp {args.output} admin@ROUTER_IP:")
    print()
    print("2. On the MikroTik router, import the script:")
    print(f"   /import {args.output}")
    print()
    print("3. Monitor the provisioning process output")
    print()
    print("4. After provisioning, change the SSH password:")
    print("   /user set orchenet password=YOUR_SECURE_PASSWORD")
    print()
    print("5. Verify the device appears in the OrcheNet web interface")
    print()


if __name__ == "__main__":
    main()
